---
management:
  endpoints:
    web:
      exposure:
        include: [loggers,health,info,metrics]
  server:
    port: 8080
spring:
  application:
    name: Automatron
  boot:
    admin:
      client:
        url: http://localhost:8080/admin
      context-path: /admin
      discovery:
        ignored-services: ['admin-server']
        services: Automatron
  messages:
    basename: i18n
  datasource:
    url: jdbc:h2:file:./h2/automatron
    driverClassName: org.h2.Driver
    username: admin
    password:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
  thymeleaf:
    check-template: false
    check-template-location: false
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
        cache: false
server:
  port: 8080

springdoc:
  writer-with-default-pretty-printer: true
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: "/doc"
    queryConfigEnabled: false
    display-request-duration: true
    groups-order: DESC
    operationsSorter: alpha
    tagsSorter: alpha
    show-extensions: true
    show-common-extensions: true
    csrf.enabled: false
