name: Build & Push
on:
  push:
    tags:
      - '**'
jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Build with Maven
        run: |
          mvn versions:set -DnewVersion=${GITHUB_REF##*/}
          mvn clean package
          ls -lah
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: touchbit
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t touchbit/automatron:latest -t touchbit/automatron:${GITHUB_REF##*/} -f Dockerfile .
          docker push --all-tags touchbit/automatron
      - name: Update DockerHub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: touchbit
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: touchbit/automatron
          short-description: TODO short-description
          readme-filepath: ./DOCKER_HUB_README.md
