name: Build & Push
on:
  push:
    tags:
      - '**'
jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Build with Maven
        run: |
          mvn versions:set -DnewVersion=${GITHUB_REF##*/}
          mvn clean package
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: touchbit
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: touchbit/automatron
      - name: Setup multiplatform build
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: windows/amd64,linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Update DockerHub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: touchbit
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: touchbit/automatron
          short-description: TODO short-description
          readme-filepath: ./DOCKER_HUB_README.md